### ISSUE TITLE
Исправить верстку выпадающего меню в шапке сайта

### ISSUE THREAD

**Issue by vierim** [vierim/YaPomogayu-frontend#1]
Выпадающее меню в шапке перекрывается другими элементами. Примеры на скриншотах:
десктоп - [https://disk.yandex.ru/i/RSp-8CWIog2qLw](https://disk.yandex.ru/i/RSp-8CWIog2qLw)
мобайл - [https://disk.yandex.ru/i/nDZmb0qUmiB2nw](https://disk.yandex.ru/i/nDZmb0qUmiB2nw)

Нужно это поведение исправить. Полагаю, что это вопрос фона и, возможно, понадобится z-index.

**Comment by AleksandrDronov** [comment]
Взял задачу
