### ISSUE TITLE
Внести правки в сущность UserInfo и производные от нее компоненты

### ISSUE THREAD

**Issue by vierim** [vierim/YaPomogayu-frontend#53]
Исполнитель - @anastasia-bazaeva 
Ревью - @BreadLinx 

Расположение компонента в Storybook - Entities/UserInfo

Нужно:
1. Изменить логику отображения кнопки "Настройки". В прошлой версии макета кнопка была неактивной для неавторизованного пользователя. Сейчас же кнопка вообще не должна отображаться, если пользователь не авторизован - [https://disk.yandex.ru/i/UVyNyGZVik19Wg](https://disk.yandex.ru/i/UVyNyGZVik19Wg)
2. В новой версии макета отказались от логики отображения общего количества заявок у реципиента и количества заявок с назначенными волонтерами - [https://disk.yandex.ru/i/Lf6gKk8rry6elw](https://disk.yandex.ru/i/Lf6gKk8rry6elw). Нужно удалить данный компонент из сущности, проекта и библиотеки иконок. 
3. Исправить ошибку в верстке вложенного в UserInfo компонента InfoContainerContent. Суть проблемы в том, что если адрес занимает больше чем одну строку, то со второй строки он выравнивается по левому краю всего компонента. Это не совсем корректно, так как выравнивание должно происходить по данной линии - [https://disk.yandex.ru/i/64a1DQhTsvLU1w](https://disk.yandex.ru/i/64a1DQhTsvLU1w)

После внесение всех правок нужно проверить, корректно ли они отображаются в Storybook.

**Comment by anastasia-bazaeva** [comment]
@vierim Привет! Увидела задачу, по пункту 2 вопрос по волонтерам - убрать нужно только количество заявок, или и ключей тоже?

**Comment by vierim** [comment]
@anastasia-bazaeva Я видимо не совсем корректно описал задачу. Пункт 2 касается только профиля Реципиента и вот этой иконки - https://disk.yandex.ru/i/Lf6gKk8rry6elw. Профиль Волонтера в рамках данного пункта не троагем.

**Comment by anastasia-bazaeva** [comment]
принято, спасибо!
