### ISSUE TITLE
Закрытие выпадающего меню в шапке

### ISSUE THREAD

**Issue by vierim** [vierim/YaPomogayu-frontend#6]
Выпадающее меню в шапке должно закрываться не только по клику на кнопку открытия, но также по клику на любой области вне этого меню и, желательно, по нажатию на Ecs.

Примечание: вообще такая логика должна быть у любого всплывающего окна, будь то фильтр, заявка на карте или создание/редактирование заявки. Поэтому, нужно подумать, как мы можем вынести это логику в какой-то отдельный хук, который можно было бы подключать к любой модалке. Но я не уверен, что создание такого хука - простая задача.

**Comment by AleksandrDronov** [comment]
Пока сделал без хука. Не уверен что возможно такой хук реализовать. Решил не зарываться на долго.
