### ISSUE TITLE
Роутинг в приложении - структура страниц и реализация

### ISSUE THREAD

**Issue by vierim** [vierim/YaPomogayu-frontend#66]
Исполнитель - @BreadLinx 
Ревью - @anastasia-bazaeva 

Нужно изучить бриф и макет и предложить структуру страниц для всех ролей в приложении - неавторизованный пользователь, текстовые страницы, реципиент, волонтер и т.д. 

Отдельно уточню, что сейчас есть 4 роута
/profile/volunteer
/profile/recipient
/profile/admin
/profile/master
Которые должны быть заменены на один - /profile. А уже внутри рендер будет происходить в зависимости от роли пользователя.

После утверждения объекта со списком страниц и доступности для ролей, нужно реализовать новый роутинг в проекте. В том числе защищенные маршруты. 
Пока я предлагаю организовать компонент ProtectedRoute в упрощенном виде - проверять доступность страницы для определенной роли. И не учитывать всякого рода permissions (они будут позже).

**Comment by BreadLinx** [comment]
![Image](https://github.com/vierim/YaPomogayu-frontend/assets/90373473/d8532841-5bb2-461a-b852-502d3cf63115)

При заходе на главную страницу в зависимости от того авторизован пользователь или нет, сайт будет вести себя по разному. Если не авторизован, то ничего не происходит и вид как на странице волонтера с ограничением некоторых функций. Если авторизован, то будет редирект на профиль, а затем другие редиректы в зависимости от роли пользователя. Смотреть схему

**Comment by anastasia-bazaeva** [comment]
Привет! Очень хорошая и понятная схема доступных по ролям роутов. Покрыт практически весь функционал. 
Есть несколько моментов, которые стоит уточнить:
1. роут /bids - это таски? Можем оставить имя роута /tasks?
2. не хватает роута для чатов, сможешь добавить?
3. Неавторизованный видит кнопку "личный кабинет", можно будет также отобразить на схеме что будет, если он перейдет по ней на /profile.

Схема доступных страниц по ролям очень наглядная. Если будет время и желание, можно дополнительно пойти от обратного - не от ролей, а от роутов, и сделать еще и карту иерархии роутов и их дочерних маршрутов, где будет указано, каким ролям тот или иной роут может быть доступен.

**Comment by vierim** [comment]
Нужно сделать две вещи:
1) Провести еще одну итерацию по просмотру макета. Мне кажется, что каких-то роутов пока не хватает. Например:
- нам точно не нужны роуты для разных типов пользователей на странице "Подтверждение/Блокировка" у администратора?
- Или, вот у такой страницы наверняка будет вложенный роут с id пользователя - https://disk.yandex.ru/i/EUsHoFcBvBPiyA

2) В иллюстрация с роутами есть некоторые проблемы читабельности. У каждого профиля повторяются те страницы, которые доступны для всех пользвателей (блог, политика и т.д.) Может есть смысл как-то иначе отображать страницы, которые доступны для всех (независимо от авторизации в целом и от роли)? Банальное решение - третий цвет. Но может ты придумаешь что-то нагляднее.

**Comment by vierim** [comment]
@anastasia-bazaeva очень хорошие замечания.
От себя добавлю, что есть смысл отобразить, что будет происходить, если авторизованный пользователь перейдет на страницу /login.

Предложение с картой иерархией классное. По сути уже из этой карты можно будет строить массив объектов, на основании которого наш роутер будет проводить все проверки. 

В бургерной у меня был такой тип для объекта, с которым работал ProtectedRouter

```
interface ProtectedRoute {
  path: string;
  anonymousOnly?: boolean;
  authOnly?: boolean;
  exact?: boolean;
  hasParrentPage?: string;
  children?: ReactNode | Element;
}
```

Возможно вам эта информация в чем-то поможет.

**Comment by BreadLinx** [comment]
![image](https://github.com/vierim/YaPomogayu-frontend/assets/90373473/8506cb0d-6689-493c-86d9-a3f3848570b5)

Переделал схему. Не стал разбирать супер частные случаи, потому что цель таски была в структуре роутов для всех ролей, кому какой роут доступен.

Например про то, что главный админ может менять роли администраторам, можно прочитать в брифе и на схеме это отображать я не стал. Показал что есть доступ к роуту выдачи прав администраторам.

**Comment by vierim** [comment]
@BreadLinx Есть сомнения относительно роутов settigns и chat для реципиента и волонтера. Но это уже детали. Какую структуру объекта будешь использовать для корректной обработки массива роутов?

**Comment by anastasia-bazaeva** [comment]
У меня есть уточнение по роуту permissions - у нас есть в ЛК админа и главного админа вложенный роут /admin/requests/, уже заложенный в проекте, и можно использовать его, т.к. название больше отражает его содержание. 
В этом разделе по макету будут находиться запросы, разбитые по вкладкам в зависимости от какой роли админу пришел запрос. У главного админа в т.ч. будет вкладка и для администраторов. Всем ролям permissions раздаваться не будут, permissions нужны только для администраторов, и их будет видеть только главный админ.
Также у Админа и Мастер Админа есть вкладка Необработанные, сейчас в проекте это также заложено как отдельный роут. 

![Image](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/05d8690c-1d46-4d2f-b549-c2559cf6aa28)

**Comment by vierim** [comment]
Есть некоторые правки относительно названий и вложенности роутов. Их нужно внести. Но это уже частности. Пора реализовывать роутинг и защищенные роуты в приложении.

**Comment by BreadLinx** [comment]
Я закончил. Кто самый смелый - жду ревью
