### ISSUE TITLE
Подготовить функционал для работы с авторизацией и разрешениями (permissions)

### ISSUE THREAD

**Issue by vierim** [vierim/YaPomogayu-frontend#75]
Исполнитель - @anastasia-bazaeva 
Ревью - @BreadLinx 

В рамках работы с ролевой моделью пользователей я вижу две большие задачи:
- предоставление доступа к определенным роутам в завивмости от типа и статуса пользователя;
- проверка permissions на рендер определенных компонентов (и некоторых роутов?)

Нужно сделать какой-то отдельный хук (или несколько), который будет в себе инкапсулировать всю логику работы с правами и ролями. Он будет сам лезть в редакс для получения данных. И будет возвращать наружу методы для проверки прав и какую-то общую переменную, что авторизация в принципе есть (типа, isAuth). 

Я это вижу примерно таким образом: у нас есть страница или компонент, у которых описаны права, для которых они доступны. Мы получаем из хука метод, который принимает права страницы и компонента и возвращает true или false в зависимости от того, соответствуют ли права текущего пользователя в редаксе тем, которые пришли в параметрах.

Детали реализации оставляю на вашу усмотрение. Если будут какие-то идеи или примеры, обязательно делитесь.

Отдельно замечу, что Платон попросил изменить константы UserRole, StatusType и PermissionType? с юнион-типов на enum. @BreadLinx, в рамках общения по данной задаче напиши свои аргументы, пожалуйста. 

---
Немного позже, когда будет более четкое понимание модели работы с авторизацией, нужно будет решить вопрос с авторизацией через VK и работой с JWT-токеном от сервере. Но это не сейчас.

**Comment by anastasia-bazaeva** [comment]
@vierim Привет! А можно у тебя уточнить, пожалуйста - у меня задача в том, чтобы сделать и протестировать хуки, или в том, чтобы пройтись и везде проставить разрешения на компонентах? А то я начала защищать компоненты на странице волонтера, и задумалась, а надо ли мне в одного все компоненты защищать в рамках моей задачи

**Comment by vierim** [comment]
@anastasia-bazaeva Привет! Я бы базово прошелся по страницам - раздал права и защитил бы пару компонентов в качестве теста / примера. Все компоненты защищать не обязательно. Мы ведь по сути страницы еще даже не начинали нормально трогать.

**Comment by anastasia-bazaeva** [comment]
Хорошо 👌 доделаю еще пару компонентов и сегодня отправлю на ревью
