### ISSUE TITLE
Компонент фильтра - упрощение подключения, фильтрация

### ISSUE THREAD

**Issue by vierim** [vierim/YaPomogayu-frontend#82]
Исполнитель - @BreadLinx 
Ревью - @anastasia-bazaeva 

В проекте есть компонент фильтра - /features/filter. В данный момент проработана его UI часть и работа с параметрами фильтрации в адресной строке. Работа с выбранными параметрами фильтра через адресную строку нужна для того, чтобы человек имел возможность отправлять кому-либо ссылку на выборку, плюс такая логика позволяет сохранять условия фильтрации при перезагрузке страницы.

Отдельно отмечу, что сейчас в процессе проработки [UI-часть для выбора диапазона времени заявок](https://github.com/vierim/YaPomogayu-frontend/issues/69), но это лишь часть UI и не завязана на логику.

**Что нужно сделать или исправить:**
1) Сейчас фильтр очень тяжело подключить на страницу. Какие-то функции, рефы, состояния, setTimeout'ы. Что именно будет в фильтре - зависит от урла страницы и не понятно, как на это влиять. Нужно все это максимально упростить и инкапсулировать в каком-то одном месте (кастомном хуке?). Чтобы на странице передавать в хук, что ты хочешь фильтровать и получать из хука базовые функции - показать фильтр, слушатель для сброса каких-то параметров фильтра (например, на странице с картой заявок у нас есть фильтр по радиусу отражения - 1км, 3км, 5км и при любом изменении масштаба карты нам нужно автоматом сбрасывать какой-то выбранный радиус).
2) Нужно продумать логику, как будет работать сама фильтрация. На каком уровне будет происходить фильтрация - на уровне хранилища или при рендере. Предполагаю, что это будет завязно на React Query кеш, поэтому пока этот момент можно просто продумать и посмотреть, как это обычно делают.
3) У меня есть ощущение, что для удобной работы с фильтром надо поменять логику работы чекбоксов. Сейчас они завязаны на дефолтное поведение элементов. Возможно, есть смысл передалать их, чтобы логика отмечен/не отмечен хранилась где-то в состоянии (самого чекбокса или родительского компонента?).

**Comment by BreadLinx** [comment]
Я думаю функционал фильтра нужно оставить как он есть. То есть установка параметров в url это верное решение.

1. Я хочу выделить фильтр в фичу. У нас есть смарт хедер, там сделаю слот для фильтра. Будет кнопка фильтра как ui и само меню фильтра.

2. Каждое меню фильтра я бы делал отдельно, а не как убер компонент. То есть например у нас есть секция "отображать", мы делаем из ui компонентов верстку, потом делаем отдельный компонент в фичи фильтра, там делаем стейт как будет выглядеть фильтр. По нажатию на чекбоксы будут меняться значения в стейте, по нажатию на кнопку применить будут меняться значения в юрле. По нажатию на сброс будут сбрасываться значения в стейте и юрле.

Я считаю что фильтр нужно сделать таким образом потому что: 
1. Все фильтры сильно различаются, выделить что-то общее сложно.
2. Это будет удобно при использовании в дальнейшем. Просто накидывается фильтр из готовых ui компонентов, делается отдельный useState внутри этого компонента и вставляется в smarheader в слот.

Через хук мне кажется будет менее правильно и сложнее для понимания. Более связано и запутано потому что опять же, где-то нам нужен радиус поиска, а где то нет

**Comment by BreadLinx** [comment]
Иллюстрация устройства фильтра

![Image](https://github.com/vierim/YaPomogayu-frontend/assets/90373473/86f8384c-f9f7-485b-b7d6-3feee1b8c561)

**Comment by BreadLinx** [comment]
Что нужно чтобы добавить новый фильтр?

1. Создаем в папке features/filter/components/filters новый компонент по аналогии с фильтрами которые там уже есть (Можно просто скопировать готовый и переименовать его).

2. Создаем в файле features/filter/types.ts новый интерфейс описывающий стейт вашего будущего фильтра по аналогии с уже созданными там. Придерживайтесь названий параметров фильтрации как они уже есть в интерфейсах до этого. Потом добавьте созданный интерфейс в общий тип IFilterValues.

3. В созданном файле меняете интерфейсы, показанные красным цветом, на свой, созданный в 2 пункте.
Меняете стейт под ваш интерфейс
![Image](https://github.com/vierim/YaPomogayu-frontend/assets/90373473/68781c8b-9571-4ce4-a599-7450da2db6b9)

4. Далее делаем структуру фильтра. У нас есть компонент FilterWrapper который добавляет основную логику фильтра, нам нужно всего лишь добавить в его проп, filterMenu меню, которое вы хотите чтобы открывалось при клике на фильтр на странице. Меню можно собрать из компонентов ui в папке фильтра.

Вы можете сделать несколько вариаций фильтра в зависимости от каких либо параметров, например роли пользователя.

5. Добавляем фильтр на страницу. На странице у нас есть компонент SmartHeader, именно в него можно вставить фильтр в его проп filter.

![Image](https://github.com/vierim/YaPomogayu-frontend/assets/90373473/63c97e6c-1652-4557-9cef-b8760ad37467)

**Comment by BreadLinx** [comment]
Нужно ревью
https://github.com/vierim/YaPomogayu-frontend/pull/96
